##Loading and preprocessing the data

Load the data
Process/transform the data (if necessary) into a format suitable for your analysis
activity <- read.csv("~/Data_Science/ReproResearch/activity.csv", stringsAsFactors=FALSE)

str(activity)

activity$date <- as.Date(activity$date)
### What is mean total number of steps taken per day?

For this part of the assignment, you can ignore the missing values in the dataset.

Calculate the total number of steps taken per day If you do not understand the difference between a histogram and a barplot, research the difference between them.

Make a histogram of the total number of steps taken each day

Calculate and report the mean and median of the total number of steps taken per day
dailySteps <- aggregate(steps~cut(date, "day"), data=activity, FUN=sum)
hist(dailySteps$steps)
mean1 <- mean(dailySteps$steps)
median1 <- median(dailySteps$steps)
table1 <- cbind(Mean=mean1, Median=median1)
table1

### What is the average daily activity pattern?

Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

intervals.df <- spread(activity, interval, steps)
intervals.df <- intervals.df[-1]
means.df <- colMeans(intervals.df, na.rm = TRUE)
plot(means.df, type="l", xlab="Interval", ylab="Mean Steps", main="Activity Plot")

### Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

which.max(means.df)

## Imputing missing values

Note that there are a number of days/intervals where there are missing values . The presence of missing days may introduce bias into some calculations or summaries of the data.

Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs) 

There are 2304 NAs in 'steps' column, which is about 13% of the data.

describe(activity)
NAsPlot <- aggr(activity, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, 
                labels=names(activity), cex.axis=.7,gap=3,
                ylab=c("Histogram of missing data", "Pattern"))
                
Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
predicitive mean used matching from the 'mice' package.

tempData <- mice(activity[-2], m=5,method="pmm", maxit=50, seed=200, print=FALSE) #selected predictive mean matching for imputation calc
summary(tempData)

imputedSteps <- complete(tempData,1) #select first imputed data set
summary(imputedSteps)

### Create a new dataset that is equal to the original dataset but with the missing data filled in.
imputedActivity <- cbind(imputedSteps,date=activity$date)
summary(imputedActivity)

### Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

dailySteps2 <- aggregate(steps~cut(date, "day"), data=imputedActivity, FUN=sum)
hist(dailySteps2$steps)

mean2 <- mean(dailySteps2$steps)
median2 <- median(dailySteps2$steps)
table2 <- cbind(Mean=mean2, Median=median2)
statsDF <- rbind(table1, table2)
rownames(statsDF) <- c("Non-Imputed", "Imputed")
#knitr
kable(statsDF)

The mean and median for the imputed data are higher, thus imputing increased the number of daily steps.

### Are there differences in activity patterns between weekdays and weekends?

For this part the weekdays function may be of some help here. Use the dataset with the filled-in missing values for this part.

a. Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

imputedActivity$weekend <- chron::is.weekend(imputedActivity$date)
imputedActivity$factor <- as.factor(imputedActivity$weekend)
levels(imputedActivity$factor)=c("weekday","weekend")

b. Make a panel plot containing a time series plot (i.e. \color{red}{\verb|type = "l"|}) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

weekdayActivity <- filter(imputedActivity, factor == "weekday")
weekendActivity <- filter(imputedActivity, factor == "weekend")

wkdy.imputedIntervals.df <- spread(weekdayActivity, interval, steps)
wkdy.imputedIntervals.df <- wkdy.imputedIntervals.df[-1:-3]
wkdy.imputedMeans.df <- colMeans(wkdy.imputedIntervals.df, na.rm = TRUE)

wknd.imputedIntervals.df <- spread(weekendActivity, interval, steps)
wknd.imputedIntervals.df <- wknd.imputedIntervals.df[-1:-3]
wknd.imputedMeans.df <- colMeans(wknd.imputedIntervals.df, na.rm = TRUE)

par(mfrow=c(2,1))

plot(wkdy.imputedMeans.df, type="l", xlab="Interval", ylab="Mean Steps", main="Weekday Activity Plot")
plot(wknd.imputedMeans.df, type="l", xlab="Interval", ylab="Mean Steps", main="Weekend Activity Plot")
